/* GeoSENSE Lab: research themes and publications shown on the Research page map.
   ---------------------------------------------------------------------------
   To add a publication, copy one entry in PUBS and edit it:
     title    exact paper title
     journal  journal or venue name (optional)
     year     publication year (optional)
     place    study area shown in the pop-up
     theme    one of the theme ids below: urban, hazard, exposure, land, health
     points   one or more [longitude, latitude] pairs (a study covering several
              places gets several points). Leave [] for reviews, methods, and tools
              with no single study area: they are listed under the map instead.
     summary  one or two sentences in plain language
     figure   optional image path, e.g. "images/dhaka-lst.png"
     link     optional DOI or journal link, e.g. "https://doi.org/10.xxxx/xxxx"
   Entries are listed newest first. Summaries are short drafts: please review them.
   Entries marked "CHECK" need a detail confirmed (venue, study area, or point).           */

window.THEMES = [
  { id: "urban", name: "Urban Studies", color: "#D7191C",
    text: "Urban heat, land surface temperature, urban form, and how cities grow and change." },
  { id: "hazard", name: "Natural Hazard and Disaster", color: "#2C7BB6",
    text: "Floods, landslides, cyclones, and tsunamis: mapping risk for preparedness, early warning, and recovery." },
  { id: "exposure", name: "Environmental Exposure", color: "#F29E4C",
    text: "Air pollution, wildfire smoke, heat, and greenness exposure measured from satellite and ground data." },
  { id: "land", name: "Land Use and Agriculture", color: "#1A9641",
    text: "Cropland, aquaculture, climate-smart agriculture, and land cover change." },
  { id: "health", name: "Public Health", color: "#8E6CC4",
    text: "Access to health care, pandemic vulnerability, and population health." }
];

window.PUBS = [
  { title: "Driving and public transit barriers to dental care in the United States",
    journal: "SSM - Population Health", year: "2026", place: "United States (national study)", theme: "health", points: [[-97.5, 38.5]],
    summary: "Measures how far people must drive or travel by public transit to reach dental care across the United States, and who faces the longest trips.",
    figure: "", link: "https://digitalscholar.lsuhsc.edu/soph_facpubs/563" },
  { title: "Geographic access to dental specialists in the United States",
    journal: "Journal of Dental Research", year: "2025", place: "United States (national study)", theme: "health", points: [[-94.5, 39.3]],
    summary: "Maps how easily people across the United States can reach dental specialists, and where specialist care is hardest to reach.",
    figure: "", link: "https://digitalscholar.lsuhsc.edu/soph_facpubs/538" },
  { title: "Wildfire impacts on New Orleans air quality: October 2024",
    journal: "Journal of the Louisiana Public Health Association", year: "2025", place: "New Orleans, Louisiana, USA", theme: "exposure", points: [[-90.07, 29.95]],
    summary: "Documents how smoke from regional wildfires in October 2024 affected air quality across New Orleans.",
    figure: "", link: "https://doi.org/10.59020/07652" },
  { title: "High activity urban event impacts local air quality of the Claiborne Corridor in New Orleans, LA",
    journal: "Journal of the Louisiana Public Health Association", year: "2025", place: "Claiborne Corridor, New Orleans, Louisiana, USA", theme: "exposure", points: [[-90.08, 29.97]],
    summary: "Measures how a large, high-traffic public event changed local air quality along the Claiborne Corridor, a community beside an elevated highway.",
    figure: "", link: "https://digitalscholar.lsuhsc.edu/jlpha/vol5/iss2/9/" },
  { title: "Spatial estimation and identification of soil lead concentration for select parks in New Orleans",
    journal: "AGU Fall Meeting Abstracts 2025", year: "2025", place: "New Orleans, Louisiana, USA", theme: "exposure", points: [[-90.05, 29.99]],
    summary: "Estimates and maps soil lead concentrations in selected New Orleans parks to identify where exposure risk is highest.",
    figure: "", link: "https://ui.adsabs.harvard.edu/abs/2025AGUFMH23J.1349M/abstract" },
  { title: "Mapping urban and peri-urban farming in New Jersey: a multi-method evaluation of OBIA and deep learning approaches",
    journal: "AGU Fall Meeting Abstracts 2025", year: "2025", place: "New Jersey, USA", theme: "land", points: [[-74.45, 40.25]],
    summary: "Compares object-based image analysis and deep learning for mapping urban and peri-urban farms across New Jersey.",
    figure: "", link: "https://ui.adsabs.harvard.edu/abs/2025AGUFMB21M.1809R/abstract" },
  { title: "Dental clinic deserts in the US: spatial accessibility analysis",
    journal: "JAMA Network Open", year: "2024", place: "United States (national study)", theme: "health", points: [[-100.5, 39.0]],
    summary: "Identifies dental care deserts, areas where people have little spatial access to a dental clinic, across the United States.",
    figure: "", link: "https://doi.org/10.1001/jamanetworkopen.2024.51625" },
  { title: "Availability of adult dental plans in the Affordable Care Act marketplaces, 2016–23",
    journal: "Health Affairs", year: "2024", place: "United States (national study)", theme: "health", points: [[-97.0, 35.8]],
    summary: "Tracks how many adult dental plans were offered in the Affordable Care Act marketplaces from 2016 to 2023 and how availability varied by place.",
    figure: "", link: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12013429/" },
  { title: "Unveiling environmental justice in two US cities through greenspace accessibility and visible greenness exposure",
    journal: "Urban Forestry & Urban Greening", year: "2024", place: "Camden and Jersey City, New Jersey, USA", theme: "exposure", points: [[-74.08, 40.73]],
    summary: "Compares how easily residents can reach greenspace and how much greenery they see day to day, revealing environmental justice gaps between neighborhoods.",
    figure: "", link: "https://doi.org/10.1016/j.ufug.2024.128493" },
  { title: "Overcoming barriers to climate-smart agriculture in South Asia",
    journal: "Nature Climate Change", year: "2024", place: "South Asia", theme: "land", points: [[78.9, 22.0]],
    summary: "Outlines the barriers that keep South Asian farmers from adopting climate-smart agriculture and what could help overcome them.",
    figure: "", link: "https://doi.org/10.1038/s41558-023-01905-z" },
  { title: "Pandemic vulnerability index of US cities: a hybrid knowledge-based and data-driven approach",
    journal: "Sustainable Cities and Society", year: "2023", place: "U.S. cities", theme: "health", points: [[-93.8, 36.4]],
    summary: "Builds a pandemic vulnerability index for U.S. cities by combining expert knowledge with data-driven methods.",
    figure: "", link: "https://doi.org/10.1016/j.scs.2023.104570" },
  { title: "Determining synergies and trade-offs between adaptation, mitigation and development in coastal socio-ecological systems in Bangladesh",
    journal: "Environmental Development", year: "2023", place: "Coastal Bangladesh", theme: "land", points: [[90.3, 22.3]],
    summary: "Examines where climate adaptation, climate mitigation, and development goals support or work against each other in coastal Bangladesh.",
    figure: "", link: "https://doi.org/10.1016/j.envdev.2023.100936" },
  { title: "“The urban poor and vulnerable are hit hardest by the heat”: a heat equity lens to understand community perceptions of climate change, urban heat islands, and green infrastructure",
    journal: "Land", year: "2023", place: "Camden, New Jersey, USA", theme: "urban", points: [[-75.11, 39.94]],
    summary: "Uses a heat equity lens to understand how residents perceive climate change, urban heat islands, and green infrastructure in their neighborhoods.",
    figure: "", link: "https://www.mdpi.com/2073-445X/12/12/2174" },
  { title: "Are leading urban centers predisposed to global risks? An analysis of the global south from COVID-19 perspective",
    journal: "Habitat International", year: "2022", place: "Cities of the Global South", theme: "health", points: [],
    summary: "Analyzes whether leading cities of the Global South are especially exposed to global risks, using the COVID-19 pandemic as a lens.",
    figure: "", link: "https://doi.org/10.1016/j.habitatint.2022.102517" },
  { title: "Impact on land surface temperature and urban heat island, due to land use/land cover change in Dhaka Metropolitan Area, using remote sensing and GIS techniques",
    journal: "Book Chapter in Re-envisioning Advances in Remote Sensing", year: "2022", place: "Dhaka, Bangladesh", theme: "urban", points: [[90.42, 23.82]],
    summary: "Measures how land use and land cover change in Dhaka has raised land surface temperature and intensified the urban heat island.",
    figure: "", link: "" },
  { title: "Assessing social vulnerability to landslide disasters in Chittagong City, Bangladesh",
    journal: "Book Chapter in Impact of Climate Change, Land Use and Land Cover, and Socio-economic Dynamics on Landslides", year: "2022", place: "Chittagong, Bangladesh", theme: "hazard", points: [[91.77, 22.33]],
    summary: "Assesses which communities in Chittagong are most socially vulnerable to landslide disasters.",
    figure: "", link: "https://link.springer.com/chapter/10.1007/978-981-16-7314-6_13" },
  { title: "Remote sensing based rapid assessment of flood crop damage using novel disaster vegetation damage index (DVDI)",
    journal: "International Journal of Disaster Risk Science", year: "2021", place: "Iowa, Nebraska, and Texas, USA", theme: "hazard", points: [[-93.5, 42.0]],
    summary: "Introduces the Disaster Vegetation Damage Index (DVDI) to rapidly map crop damage after floods from satellite imagery.",
    figure: "", link: "https://doi.org/10.1007/s13753-020-00305-7" },
  { title: "Machine learning on the COVID-19 pandemic, human mobility and air quality: a review",
    journal: "IEEE Access", year: "2021", place: "Global review", theme: "health", points: [[11.815336, 50.367167]],
    summary: "Reviews how machine learning has been used to study the COVID-19 pandemic, human mobility, and air quality.",
    figure: "", link: "https://doi.org/10.1109/ACCESS.2021.3079121" },
  { title: "Public perceptions about COVID-19 vaccines: policy implications from US spatiotemporal sentiment analytics",
    journal: "Healthcare", year: "2021", place: "United States (national study)", theme: "health", points: [[-101.5, 36.2]],
    summary: "Analyzes public sentiment about COVID-19 vaccines across U.S. states and over time, and what it means for vaccination policy.",
    figure: "", link: "https://doi.org/10.3390/healthcare9091110" },
  { title: "Flood monitoring and crop damage assessment",
    journal: "Book Chapter in Agro-geoinformatics: Theory and Practice", year: "2021", place: "", theme: "hazard", points: [[-95.406815, 40.153995]],
    summary: "Describes how satellite data can be used to monitor floods and assess the resulting damage to crops.",
    figure: "", link: "https://link.springer.com/chapter/10.1007/978-3-030-66387-2_16" },
  { title: "Covid-19 digital contact-tracing: a doorway to well-being or a backdoor to security vulnerabilities?",
    journal: "IEEE International Conference on Big Data", year: "2021", place: "", theme: "health", points: [[-74.746324, 40.655207]],
    summary: "Weighs the public health benefits of digital COVID-19 contact tracing against its privacy and security risks.",
    figure: "", link: "https://ieeexplore.ieee.org/document/9671880" },
  { title: "Application of geospatial technologies in developing a dynamic landslide early warning system in a humanitarian context: the Rohingya refugee crisis in Cox’s Bazar, Bangladesh",
    journal: "Geomatics, Natural Hazards and Risk", year: "2020", place: "Cox’s Bazar, Bangladesh", theme: "hazard", points: [[92.15, 21.2]],
    summary: "Develops a dynamic landslide early warning system for the Rohingya refugee camps and host communities in Cox’s Bazar.",
    figure: "", link: "https://doi.org/10.1080/19475705.2020.1730988" },
  { title: "Modelling future land use land cover changes and their impacts on land surface temperatures in Rajshahi, Bangladesh",
    journal: "Remote Sensing Applications: Society and Environment", year: "2020", place: "Rajshahi, Bangladesh", theme: "urban", points: [[88.6, 24.37]],
    summary: "Projects future land use change in Rajshahi and estimates how it will raise land surface temperatures.",
    figure: "", link: "https://www.sciencedirect.com/science/article/pii/S2352938520300495" },
  { title: "A systematic review on case studies of remote-sensing-based flood crop loss assessment",
    journal: "Agriculture", year: "2020", place: "Global review", theme: "hazard", points: [[-95.831883, 42.118785]],
    summary: "Systematically reviews case studies that use remote sensing to assess crop losses from floods.",
    figure: "", link: "https://doi.org/10.3390/agriculture10040131" },
  { title: "Fishpond mapping by spectral and spatial-based filtering on Google Earth Engine: a case study in Singra Upazila of Bangladesh",
    journal: "Remote Sensing", year: "2020", place: "Singra, Bangladesh", theme: "land", points: [[89.13, 24.5]],
    summary: "Maps fishponds from satellite imagery on Google Earth Engine using spectral and spatial filtering.",
    figure: "", link: "https://doi.org/10.3390/rs12172692" },
  { title: "Evaluating the effects of digital elevation models in landslide susceptibility mapping in Rangamati District, Bangladesh",
    journal: "Remote Sensing", year: "2020", place: "Rangamati, Bangladesh", theme: "hazard", points: [[92.18, 22.65]],
    summary: "Compares how the choice of digital elevation model changes landslide susceptibility maps for the Rangamati hills.",
    figure: "", link: "https://doi.org/10.3390/rs12172718" },
  { title: "Prediction of seasonal urban thermal field variance index using machine learning algorithms in Cumilla, Bangladesh",
    journal: "Sustainable Cities and Society", year: "2020", place: "Cumilla, Bangladesh", theme: "urban", points: [[91.18, 23.46]],
    summary: "Uses machine learning to predict the seasonal urban thermal field variance index and identify heat-stressed areas of Cumilla.",
    figure: "", link: "https://doi.org/10.1016/j.scs.2020.102542" },
  { title: "In-season major crop-type identification for US cropland from Landsat images using crop-rotation pattern and progressive data classification",
    journal: "Agriculture", year: "2019", place: "Iowa, USA", theme: "land", points: [[-93.0, 41.8]],
    summary: "Identifies major crop types during the growing season from Landsat imagery by using each field's crop rotation history.",
    figure: "", link: "https://doi.org/10.3390/agriculture9010017" },
  { title: "Rapid flood progress monitoring in cropland with NASA SMAP",
    journal: "Remote Sensing", year: "2019", place: "Houston, Texas, USA", theme: "hazard", points: [[-95.37, 29.76]],
    summary: "Tracks how floods spread and recede across cropland around Houston, Texas, using NASA SMAP soil moisture data.",
    figure: "", link: "https://doi.org/10.3390/rs11020191" },
  { title: "Improvement and validation of NASA/MODIS NRT global flood mapping",
    journal: "Remote Sensing", year: "2019", place: "Global", theme: "hazard", points: [[-114.583823, 42.626298]],
    summary: "Improves and validates NASA's near-real-time global flood maps from MODIS.",
    figure: "", link: "https://doi.org/10.3390/rs11020205" },
  { title: "Spatial–temporal landscape pattern change under rapid urbanization",
    journal: "Journal of Applied Remote Sensing", year: "2019", place: "National Capital Region of Delhi, India", theme: "urban", points: [[77.21, 28.61]],
    summary: "Examines how landscape patterns changed over two decades of rapid urbanization in the National Capital Region of Delhi, India.",
    figure: "", link: "https://doi.org/10.1117/1.JRS.13.024503" },
  { title: "Crop growth condition assessment at county scale based on heat-aligned growth stages",
    journal: "Remote Sensing", year: "2019", place: "Carroll County, Iowa, USA", theme: "land", points: [[-94.86, 42.06]],
    summary: "Assesses crop growth condition at the county scale by aligning growth stages with accumulated heat.",
    figure: "", link: "https://doi.org/10.3390/rs11202439" },
  // CHECK: study area placed in the Midwest; confirm or move the pin
  { title: "Relationship between soil moisture and crop yield in America during a drought",
    journal: "American Geophysical Union, Fall Meeting 2019", year: "2019", place: "United States", theme: "land", points: [[-89.5, 40.0]],
    summary: "Examines how soil moisture related to crop yields across the United States during a drought year.",
    figure: "", link: "https://ui.adsabs.harvard.edu/abs/2019AGUFM.B51B..08Z/abstract" },
  { title: "Tropical cyclone hazard to remote home for the Rohingya at Bhasan Char in Bangladesh",
    journal: "Abstract in the UCL International Conference on the Rohingya Crisis in Comparative Perspective", year: "2019", place: "Bhasan Char, Bangladesh", theme: "hazard", points: [[91.39, 22.37]],
    summary: "Assesses the tropical cyclone hazard facing Bhasan Char, the remote island chosen to relocate Rohingya refugees.",
    figure: "", link: "" },
  { title: "Comparison between directional distribution of observed and forecasted trajectories of hurricane in North Atlantic Basin",
    journal: "International Conference on Disaster Risk Management (ICDRM 2019)", year: "2019", place: "North Atlantic Basin", theme: "hazard", points: [[-60.0, 25.0]],
    summary: "Compares the directional spread of observed and forecasted hurricane tracks in the North Atlantic.",
    figure: "", link: "" },
  { title: "Crop field boundary delineation using historical crop rotation pattern",
    journal: "2019 8th International Conference on Agro-Geoinformatics", year: "2019", place: "Iowa, USA", theme: "land", points: [[-93.663815, 41.608906]],
    summary: "Delineates crop field boundaries by using each field's history of crop rotations.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8820240" },
  { title: "Prediction of field level crop types using Markov chain modeling on crop rotation pattern",
    journal: "American Geophysical Union, Fall Meeting 2019", year: "2019", place: "Iowa, USA", theme: "land", points: [[-93.663815, 41.608906]],
    summary: "Predicts which crop will be planted in each field by modeling crop rotation patterns as a Markov chain.",
    figure: "", link: "https://ui.adsabs.harvard.edu/abs/2019AGUFM.B51B..02R/abstract" },
  { title: "Calibration of crop growth simulation model for irrigated cropland using remote sensing derived leaf area index",
    journal: "American Geophysical Union, Fall Meeting 2019", year: "2019", place: "", theme: "land", points: [],
    summary: "Calibrates a crop growth simulation model for irrigated cropland using leaf area index derived from satellite imagery.",
    figure: "", link: "https://ui.adsabs.harvard.edu/abs/2019AGUFM.B51N2426Y/abstract" },
  { title: "Full stack web development of a geospatial information service system for intelligently irrigated agriculture",
    journal: "2019 8th International Conference on Agro-Geoinformatics", year: "2019", place: "", theme: "land", points: [],
    summary: "Develops a web-based geospatial information system to support intelligent irrigation decisions.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8820551" },
  { title: "Selection of Landsat 8 OLI band combinations for land use and land cover classification",
    journal: "2019 8th International Conference on Agro-Geoinformatics", year: "2019", place: "", theme: "land", points: [],
    summary: "Tests which combinations of Landsat 8 bands give the most accurate land use and land cover classification.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8820595" },
  { title: "Cloud environment for disseminating NASS cropland data layer",
    journal: "2019 8th International Conference on Agro-Geoinformatics", year: "2019", place: "", theme: "land", points: [],
    summary: "Builds a cloud environment for distributing the USDA NASS Cropland Data Layer to users.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8820465" },
  { title: "Building near-real-time MODIS data fusion workflow to support agricultural decision-making applications",
    journal: "2019 8th International Conference on Agro-Geoinformatics", year: "2019", place: "", theme: "land", points: [],
    summary: "Builds a near-real-time MODIS data fusion workflow to support agricultural decision-making.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8820229" },
  { title: "Clustering Indian Ocean tropical cyclone tracks by the standard deviational ellipse",
    journal: "Climate", year: "2018", place: "Indian Ocean", theme: "hazard", points: [[80.0, -8.0]],
    summary: "Groups Indian Ocean tropical cyclone tracks into clusters using the standard deviational ellipse.",
    figure: "", link: "https://www.mdpi.com/2225-1154/6/2/39" },
  { title: "Developing a dynamic web-GIS based landslide early warning system for the Chittagong metropolitan area, Bangladesh",
    journal: "ISPRS International Journal of Geo-Information", year: "2018", place: "Chittagong, Bangladesh", theme: "hazard", points: [[91.82, 22.36]],
    summary: "Builds a web-GIS landslide early warning system that updates with rainfall for the Chittagong metropolitan area.",
    figure: "", link: "https://doi.org/10.3390/ijgi7120485" },
  { title: "Classification of cities in Bangladesh based on remote sensing derived spatial characteristics",
    journal: "Journal of Urban Management", year: "2018", place: "Bangladesh", theme: "urban", points: [[90.0, 24.2]],
    summary: "Classifies Bangladeshi cities by their spatial characteristics measured from satellite imagery.",
    figure: "", link: "https://doaj.org/article/d7b8731098bc4fed92b3c14e3a230963" },
  { title: "Using machine learning approach to evaluate the PM2.5 concentrations in China from 1998 to 2016",
    journal: "2018 7th International Conference on Agro-Geoinformatics", year: "2018", place: "China", theme: "exposure", points: [[105.0, 34.5]],
    summary: "Uses machine learning to estimate PM2.5 air pollution concentrations across China from 1998 to 2016.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8475987" },
  { title: "Impact of climate change on soil salinity: a remote sensing based investigation in coastal Bangladesh",
    journal: "2018 7th International Conference on Agro-Geoinformatics", year: "2018", place: "Coastal Bangladesh", theme: "land", points: [[89.5, 22.3]],
    summary: "Uses satellite data to investigate how climate change is affecting soil salinity in coastal Bangladesh.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8476036" },
  { title: "Land use/land cover classification and change analysis for Ganges River Basin from 2000 to 2010",
    journal: "American Geophysical Union, Fall Meeting 2018", year: "2018", place: "Ganges River Basin", theme: "land", points: [[83.0, 25.5]],
    summary: "Classifies land use and land cover across the Ganges River Basin and analyzes how it changed from 2000 to 2010.",
    figure: "", link: "https://ui.adsabs.harvard.edu/abs/2018AGUFM.B23J2661Y/abstract" },
  { title: "Land use and land cover classification for Bangladesh 2005 on Google Earth Engine",
    journal: "2018 7th International Conference on Agro-Geoinformatics", year: "2018", place: "Bangladesh", theme: "land", points: [[90.2, 23.4]],
    summary: "Produces a land use and land cover map of Bangladesh for 2005 using Google Earth Engine.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8475976" },
  { title: "Agriculture flood mapping with Soil Moisture Active Passive (SMAP) data: a case of 2016 Louisiana flood",
    journal: "2017 6th International Conference on Agro-Geoinformatics", year: "2017", place: "Louisiana, USA", theme: "hazard", points: [[-91.1, 30.5]],
    summary: "Maps flooded cropland during the August 2016 Louisiana flood using NASA SMAP soil moisture data.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8047062" },
  { title: "The state of the art of spaceborne remote sensing in flood management",
    journal: "Natural Hazards", year: "2017", place: "Global review", theme: "hazard", points: [],
    summary: "Reviews how satellite remote sensing supports each stage of flood management.",
    figure: "", link: "https://doi.org/10.1007/s11069-016-2601-9" },
  { title: "Landslide initiation and runout susceptibility modeling in the context of hill cutting and rapid urbanization: a combined approach of weights of evidence and spatial multi-criteria",
    journal: "Journal of Mountain Science", year: "2017", place: "Chittagong, Bangladesh", theme: "hazard", points: [[91.79, 22.4]],
    summary: "Models where landslides are likely to start and how far they may travel in hills affected by hill cutting and rapid urbanization.",
    figure: "", link: "https://doi.org/10.1007/s11629-016-4220-z" },
  { title: "Exploring the association of land cover changes and landslides in the Chittagong Hill Tracts (CHT): a remote sensing perspective",
    journal: "International Conference on Disaster Risk Mitigation", year: "2017", place: "Chittagong Hill Tracts, Bangladesh", theme: "hazard", points: [[92.05, 22.95]],
    summary: "Uses satellite imagery to explore how land cover change is linked to landslides in the Chittagong Hill Tracts.",
    figure: "", link: "" },
  // CHECK: title in papers.csv looked cut off; confirm the full title
  { title: "Crop Fraction Layer (CFL) datasets derived through MODIS and Landsat for the Continental US",
    journal: "2017 6th International Conference on Agro-Geoinformatics", year: "2017", place: "Continental United States", theme: "land", points: [[-99.0, 38.0]],
    summary: "Derives crop fraction layers for the continental United States from MODIS and Landsat imagery.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8047068" },
  { title: "Developing geospatial Web service and system for SMAP soil moisture monitoring",
    journal: "2017 6th International Conference on Agro-Geoinformatics", year: "2017", place: "", theme: "land", points: [],
    summary: "Develops a geospatial web service and system for monitoring soil moisture with NASA SMAP data.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8047066" },
  { title: "Performance improvement on a Web Geospatial service for the remote sensing flood-induced crop loss assessment web application using vector tiling",
    journal: "2017 6th International Conference on Agro-Geoinformatics", year: "2017", place: "", theme: "hazard", points: [],
    summary: "Speeds up a web application for assessing flood-induced crop loss by using vector tiling.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8047053" },
  { title: "Integrating OGC Web Processing Service with cloud computing environment for Earth Observation data",
    journal: "2017 6th International Conference on Agro-Geoinformatics", year: "2017", place: "", theme: "land", points: [],
    summary: "Integrates the OGC Web Processing Service with cloud computing to process Earth observation data.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8047065" },
  { title: "Extract flood duration from Dartmouth Flood Observatory flood product",
    journal: "2017 6th International Conference on Agro-Geoinformatics", year: "2017", place: "", theme: "hazard", points: [],
    summary: "Extracts flood duration information from the Dartmouth Flood Observatory flood product.",
    figure: "", link: "https://ieeexplore.ieee.org/document/8047064" },
  { title: "The role of big data in disaster management",
    journal: "International Conference on Disaster Risk Mitigation", year: "2017", place: "", theme: "hazard", points: [],
    summary: "Discusses how big data can support each stage of disaster management.",
    figure: "", link: "" },
  { title: "A review of remote sensing in flood assessment",
    journal: "2016 Fifth International Conference on Agro-Geoinformatics", year: "2016", place: "Global review", theme: "hazard", points: [],
    summary: "Reviews how remote sensing has been used to assess floods.",
    figure: "", link: "https://ieeexplore.ieee.org/document/7577655" },
  { title: "Comparison of selected noise reduction techniques for MODIS daily NDVI: an empirical analysis on corn and soybean",
    journal: "2016 Fifth International Conference on Agro-Geoinformatics", year: "2016", place: "", theme: "land", points: [],
    summary: "Compares noise reduction techniques for MODIS daily NDVI time series of corn and soybean.",
    figure: "", link: "https://ieeexplore.ieee.org/document/7577661" },
  { title: "Regression based corn yield assessment using MODIS based daily NDVI in Iowa State",
    journal: "2016 Fifth International Conference on Agro-Geoinformatics", year: "2016", place: "Iowa, USA", theme: "land", points: [[-92.6, 42.1]],
    summary: "Estimates corn yield in Iowa from daily MODIS NDVI using regression models.",
    figure: "", link: "https://ieeexplore.ieee.org/document/7577657" },
  { title: "Study of the vegetation index-meteorological factor correlation adjusted by accumulated growing degree days",
    journal: "2016 Fifth International Conference on Agro-Geoinformatics", year: "2016", place: "", theme: "land", points: [],
    summary: "Examines how vegetation indices relate to weather factors once adjusted for accumulated growing degree days.",
    figure: "", link: "https://ieeexplore.ieee.org/document/7577672" },
  { title: "Online parameterization for WOFOST for United States using open geospatial standards",
    journal: "2016 Fifth International Conference on Agro-Geoinformatics", year: "2016", place: "United States", theme: "land", points: [[-96.0, 41.0]],
    summary: "Parameterizes the WOFOST crop growth model for the United States online using open geospatial standards.",
    figure: "", link: "https://ieeexplore.ieee.org/document/7577658" },
  { title: "Landslide inventory in an urban setting in the context of Chittagong Metropolitan Area, Bangladesh",
    journal: "3rd International Conference on Advances in Civil Engineering 2016", year: "2016", place: "Chittagong, Bangladesh", theme: "hazard", points: [[91.84, 22.38]],
    summary: "Builds an inventory of landslides in the urban setting of the Chittagong Metropolitan Area.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "Disaster management and city resilience",
    journal: "", year: "2015", place: "", theme: "hazard", points: [],
    summary: "Discusses how disaster management can strengthen the resilience of cities.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "Landslide inventory report of Chittagong Metropolitan Area, Bangladesh",
    journal: "", year: "2014", place: "Chittagong, Bangladesh", theme: "hazard", points: [[91.86, 22.35]],
    summary: "Reports an inventory of landslides recorded across the Chittagong Metropolitan Area.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "Social survey report on landslide vulnerability in Chittagong Metropolitan Area, Bangladesh",
    journal: "", year: "2014", place: "Chittagong, Bangladesh", theme: "hazard", points: [[91.81, 22.39]],
    summary: "Reports a household survey of social vulnerability to landslides in the Chittagong Metropolitan Area.",
    figure: "", link: "" },
  { title: "Simulating land cover changes and their impacts on land surface temperature in Dhaka, Bangladesh",
    journal: "Remote Sensing", year: "2013", place: "Dhaka, Bangladesh", theme: "urban", points: [[90.4, 23.78]],
    summary: "Simulates future land cover change in Dhaka and its impact on land surface temperature.",
    figure: "", link: "https://doi.org/10.3390/rs5115969" },
  { title: "Coastal community resilience to tsunami: a study on planning capacity and social capacity, Dichato, Chile",
    journal: "IOSR Journal of Humanities and Social Science", year: "2013", place: "Dichato, Chile", theme: "hazard", points: [[-72.93, -36.55]],
    summary: "Examines the planning and social capacity that shaped the coastal town of Dichato's resilience after the 2010 tsunami.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "Decentralization in urban land-use planning in Bangladesh: rationality of the scene behind a screen",
    journal: "", year: "2013", place: "Bangladesh", theme: "urban", points: [[89.8, 23.9]],
    summary: "Examines how decentralization works in practice in urban land-use planning in Bangladesh.",
    figure: "", link: "" },
  { title: "Disaster as an opportunity to enhance community resilience: lesson learnt from Chilean coast",
    journal: "Journal of Bangladesh Institute of Planners", year: "2012", place: "Chilean coast", theme: "hazard", points: [[-73.05, -37.0]],
    summary: "Draws lessons from post-disaster recovery on the Chilean coast on how disasters can be used to strengthen community resilience.",
    figure: "", link: "" },
  { title: "Quantifying urban form - compactness versus sprawl: an analysis of Chittagong and Sylhet metropolitan cities",
    journal: "Jahangirnagar University Planning Review", year: "2012", place: "Chittagong and Sylhet, Bangladesh", theme: "urban", points: [[91.87, 24.9]],
    summary: "Measures whether Chittagong and Sylhet are growing compactly or sprawling.",
    figure: "", link: "" },
  { title: "An overview on rapid urbanization and induced disaster risk factors in Bangladesh",
    journal: "Planned Town: Balanced Development, BIP", year: "2012", place: "Bangladesh", theme: "hazard", points: [[90.3, 23.6]],
    summary: "Reviews how rapid urbanization in Bangladesh creates and increases disaster risk.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "A state of art review on internal curing of concrete and its prospect for Bangladesh",
    journal: "", year: "2011", place: "Bangladesh", theme: "urban", points: [],
    summary: "Reviews internal curing of concrete and its prospects for construction in Bangladesh.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "Compact township as the conceptual planning approach to rural settlement development in Bangladesh: a case study of Putia Union, Shibpur Upazila, Narsingdi District",
    journal: "", year: "2010", place: "Putia Union, Narsingdi, Bangladesh", theme: "urban", points: [[90.73, 24.02]],
    summary: "Proposes compact townships as a planning approach for rural settlements, using Putia Union as a case study.",
    figure: "", link: "" },
  // CHECK: add journal/venue
  { title: "Impact of roadside commercialization on transportation performance: a case of Satmosjid Road, Dhaka",
    journal: "", year: "2009", place: "Satmosjid Road, Dhaka, Bangladesh", theme: "urban", points: [[90.375, 23.745]],
    summary: "Examines how commercial development along Satmosjid Road in Dhaka affects traffic flow and transportation performance.",
    figure: "", link: "" }
];
