/* Colour theme: LSU Health New Orleans purple and gold. */
/* GeoSENSE Lab: Research page, color-coded themes beside a zoomable world map of publications.
   Data comes from js/publications.js. Land shapes: Natural Earth (world-atlas), packed as bits.
   Zoom: mouse wheel, + / - buttons, double-click, or pinch. Drag to move around.              */
(function () {
  function initResearchMap() {
    const box = document.getElementById("pubmap");
    if (!box || !window.PUBS || box.dataset.ready) return false; // not loaded yet, or already built
    box.dataset.ready = "yes";
    const MAPS = {
      world: {
        land: {
          lon0: -180,
          lat1: 84,
          step: 1,
          W: 360,
          H: 144,
          bits: "AAAAAAAAAAAAAAAAAAAAAADg/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/v8/AOD//z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+///D/////5//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAH/j/+//////8PAAAAgB0AAHgAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAOD//wP8//////8BAACAfx4AAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAA4+I73//n///////8AAAAAfwAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAOAQACDwP4D///////8BAAAAPAQAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAADzAgPP5H8D//////38AAAAAAAAAAAAA4AEAAAD+DwAAAAAAAAAAAAAAAAAAAIC/g7PfBwAA/v////8AAAAAAAAAAADgBwAAwP//PwAA4B8AAAAAAAAAAAAAAAAMAAB8AgAA+P////8AAAAAAAAAAABwAAAA/P//AwAAAAAAAAAAAAAAAAAAAP8Ahvc5OwAA8P///38AAAAAAAAAAAAcAADg////34cHAAcAAAAAAAAAAAAAgN9/xzf8RwAA4P///z8AAAAAAAAAAAAPAB7g//////8fgD8AAAAAAQAAAAAAAO//B3f8/wsA4P///z8AAAAAAAAAAAAPAG////////8f2f8HAAAAAAD4HwAAAAD4H/D4/38A4P///xMAAAAAAPAHAAAAgN//////////////DwAAAAD+///h/4//H+/Bg/8BwP7//w8AAAAAwP8fAAAAj9///////////////88/A+D///////8DB8TPB/4AAP///wAAAAAA8P//AwDjf77/////////////////DwD////////////vh/kPwP//BwAAAAAA/P//H/P//5//////////////////34H8////////////Afw/gP//AQAQAAAA/v8fH////+///////////////////vD///////////9fAPwYgP8PAOA/AAAA/+N/8P//////////////////////QID4///////////Pw/0DAP8HAMAfAACA//F//v////////////////////8/AAP4///////////BBPAHAP4HAAAAAADg//z///////////////////////9/AID///////////8AQ4ABAPwBAAAAAAD8P/7///////////////////////9fAMD//////////z8AwA8AAPgBAAAAAAD+H/7/////////////////////Of8BAID///z//////z8AwD8AAMABAAAAAAD+P/z///////////////////9/wH8AAAD8MwD//////x8AwH8MAAAAAAAAAAD+P2D///////////////////95cAAAAACAAwD8/////38AwP8eAAAAAAAAgAGcH/D//////////////////wEAOAAAAADADgDA/////38AgP8/AAAAAAAAwANAH/T//////////////////wAAfgAAAAAwAAAA//////8PgP8/AAAAAAAAwAFwD/7/////////////////PwAAfwAAAAAGAAAA//////8/wP//AAAAAAAAwAOwA/7/////////////////DwCAPwAAAIAAAAAA/v//////8///BwAAAAAAOAcgcP//////////////////HwAAHwAAAAAAAACA+P//////4///DwAAAAAAOA74/////////////////////wUADwAAAAAAAAAA8P//////4///DwAAAAAAGD///////////////////////wUAAwAAAAAAAAAA8P//////7///FwAAAAAAAB///////////////////////wUAAgAAAAAAAAAA0P//////////DAAAAAAAgOH//////////////////////w0AAAAAAAAAAAAAYP////////8xLAAAAAAAAPz//////////////////////wwAAAAAAAAAAAAAAP7//////38HfgAAAAAAgP///////////////////////wQAAAAAAAAAAAAAAP3///////8HUAAAAAAAAP7/////////////////////fwQAAAAAAAAAAAAAAP////////+XAAAAAAAAAPz///93/D/+////////////PwwAAAAAAAAAAAAAAP////////9/AAAAAAAAAPj//f9j/g/+////////////HwAAAAAAAAAAAAAAAP////////8MAAAAAAAAAPj/+P8B/Mf/////////////DwQAAAAAAAAAAAAAAP///////z8AAAAAAAAAcPzH8/8A8I//////////////Bx4AAAAAAAAAAAAAAP///////x8AAAAAAAAA+H+Aw/8AwA/+//////////9/AA8AAAAAAAAAAAAAAP///////x8AAAAAAAAA+D8Aj//w4R/8//////////8/AAAAAAAAAAAAAAAAAP///////wMAAAAAAAAA+B8wuE/+/z/+/////////98fAAMAAAAAAAAAAAAAAP///////wMAAAAAAAAA+A8wEMf//x/+/////////0cOAAMAAAAAAAAAAAAAAP7//////wEAAAAAAAAA+A8AAM7//x/8/////////wMOAAEAAAAAAAAAAAAAAP7//////wAAAAAAAAAA+AcABob//z/8/////////zccwAEAAAAAAAAAAAAAAPz//////wAAAAAAAAAAQOB/AAQ2/////////////x8c8AEAAAAAAAAAAAAAAPj//////wAAAAAAAAAAQPx/AAAA/////////////w8Y/gEAAAAAAAAAAAAAAPD/////fwAAAAAAAAAA4P8/AAAA/////////////w+EGwAAAAAAAAAAAAAAAMD/////HwAAAAAAAAAA8P9/AACA/////////////x/AAwAAAAAAAAAAAAAAAID/////DwAAAAAAAAAA+P//BwaA/////////////x/AAAAAAAAAAAAAAAAAAID9////BwAAAAAAAAAA/P//D3+E/////////////z9AAAAAAAAAAAAAAAAAAAD5////BwAAAAAAAAAA/P//f////////////////x8AAAAAAAAAAAAAAAAAAADy/x8GBgAAAAAAAAAA/P/////v/8///////////z8AAAAAAAAAAAAAAAAAAAD0/w8ABgAAAAAAAAAA/v////+//4///////////z8AAAAAAAAAAAAAAAAAAADu/wcADgAAAAAAAACA//////8f/x/+/////////x8AAAAAAAAAAAAAAAAAAACI/wcALAAAAAAAAADA//////8//z/g/////////w8AAAAAAAAAAAAAAAAAAACQ/wcACAAAAAAAAADg//////9//r+A/////////wcAAAAAAAAAAAAAAAAAAAAQ/wMAAAAAAAAAAADg//////9//n8cgP///////ycAAAAAAAAAAAAAAAAAAAAA/gMAAAAAAAAAAADw////////+P9/AP///////xEAAAAAAAAAAAAAAAAAAAAA/AMAHQAAAAAAAADw////////+P//APz/f///fxAAAAAAAAAAAAAAAAAAAAAA+AcAYAAAAAAAAAD4////////+f9/APz/B///BgAAAAAAAAAAAAAAAAAAAAAA/AccgAEAAAAAAADw////////8f9/AOD/B/5/AAAAAAAAAAAAAAAAAQAAAAAA+A8eADgAAAAAAADw////////4f8/AOD/Afw/BgAAAAAAAAAAAAAAAAAAAAAA8J8PAPwCAAAAAADw////////4/8fAOD/APw/AgAAAAAAAAAAAAAAAAAAAAAAgP8PAAAAAAAAAADw////////x/8HAOB/APx/ADAAAAAAAAAAAAAAAAAAAAAAAP4PAAAAAAAAAAD4////////h/8BAOA/APz/ADAAAAAAAAAAAAAAAAAAAAAAAID/AAAAAAAAAAD4////////j/8AAMAPAMD/ATAAAAAAAAAAAAAAAAAAAAAAAAD/AQAAAAAAAAD4////////nx8AAMAPAMD/ATAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAD4////////vwcAAIAPAMD/AcAAAAAAAAAAAAAAAAAAAAAAAADgAQAAAAAAAAD4////////fwAAAIAPAMD8AQABAAAAAAAAAAAAAAAAAAAAAADAAAgAAAAAAADw////////f2AAAAAPAID4AUACAAAAAAAAAAAAAAAAAAAAAADAAe9TAAAAAADg/////////34AAAAPAEBwAAgAAAAAAAAAAAAAAAAAAAAAAAAAE+9/AAAAAADA/////////38AAAAXAEAgAAQCAAAAAAAAAAAAAAAAAAAAAAAAz///AAAAAACA/////////z8AAAASAMAAAIACAAAAAAAAAAAAAAAAAAAAAAAAyP//AQAAAACA/////////z8AAAAwAIAAAEAHAAAAAAAAAAAAAAAAAAAAAAAAgP//AwAAAAAA/v///////x8AAAAwAAADAAMBAAAAAAAAAAAAAAAAAAAAAAAAwP//fwAAAAAA/A/+/////x8AAAAAAAAHAAcAAAAAAAAAAAAAAAAAAAAAAAAAgP///wAAAAAAEAD8/////w8AAAAAADAGwAcAAAAAAAAAAAAAAAAAAAAAAAAAgP///wEAAAAAAADA/////wcAAAAAAGAG4AEAAAAAAAAAAAAAAAAAAAAAAAAA4P///wEAAAAAAADA/////wMAAAAAAMAM+AMAAAAAAAAAAAAAAAAAAAAAAAAA4P///wMAAAAAAADg/////wEAAAAAAIAL/gMQAAAAAAAAAAAAAAAAAAAAAAAA8P///wMAAAAAAADg////fwAAAAAAAIAH/vMQAAAAAAAAAAAAAAAAAAAAAAAA8P///wcAAAAAAADg////PwAAAAAAAAAP/gMAAQAAAAAAAAAAAAAAAAAAAAAA+P///38AAAAAAADg////PwAAAAAAAAAO/DmAAwAAAAAAAAAAAAAAAAAAAAAA+P///38BAAAAAADA////HwAAAAAAAAA+/DkA8gAAAAAAAAAAAAAAAAAAAAAA8P////8fAAAAAACA////DwAAAAAAAAA8wChE/gcAAAAAAAAAAAAAAAAAAAAA+P////8/AAAAAACA////BwAAAAAAAAA4AEAA8B8AAAAAAAAAAAAAAAAAAAAA+P//////AQAAAAAA////BwAAAAAAAAAwAEAAxD8NAAAAAAAAAAAAAAAAAAAA+P//////AQAAAAAA////BwAAAAAAAADAAQAAxP+AAAAAAAAAAAAAAAAAAAAA8P//////AQAAAAAA/v//BwAAAAAAAACAHwAAwH8ABAAAAAAAAAAAAAAAAAAA4P//////AQAAAAAA/v//BwAAAAAAAAAAQFYEAMcAAAAAAAAAAAAAAAAAAAAA4P//////AAAAAAAA/v//DwAAAAAAAAAAAAgBAIABMAAAAAAAAAAAAAAAAAAAwP//////AAAAAAAA/v//DwAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAgP////9/AAAAAAAA/P//DwAAAAAAAAAAAAAAAQQAAAAAAAAAAAAAAAAAAAAAgP////8/AAAAAAAA/v//HyAAAAAAAAAAAACAHwQAAAAAAAAAAAAAAAAAAAAAAP////8fAAAAAAAA/v//HyAAAAAAAAAAAADADwwAAAAAAAAAAAAAAAAAAAAAAP////8fAAAAAAAA////HzAAAAAAAAAAAADsDxwAAAAAAAAAAAAAAAAAAAAAAP7///8fAAAAAAAA////DzgAAAAAAAAAAAD/DxwAAAAAAAAAAAAAAAAAAAAAAPj///8fAAAAAAAA////Dz8AAAAAAAAAAAD/Pz4AAAiAAAAAAAAAAAAAAAAAAOD///8fAAAAAAAA////Ax8AAAAAAAAAAMD//z4AAABAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA////AB8AAAAAAAAAAMD//z8AAAAAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA/v9/AB8AAAAAAAAAAOD//38AAAAAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA/v9/AB8AAAAAAAAAAPz///8BAAEAAAAAAAAAAAAAAAAAAMD///8HAAAAAAAA/P9/gA8AAAAAAAAAgP////8BAAIAAAAAAAAAAAAAAAAAAMD///8DAAAAAAAA/P//gA8AAAAAAAAAwP////8DAAAAAAAAAAAAAAAAAAAAAMD//38AAAAAAAAA/P9/AA8AAAAAAAAAwP////8HAAAAAAAAAAAAAAAAAAAAAOD//x8AAAAAAAAA+P9/AAcAAAAAAAAA4P////8PAAAAAAAAAAAAAAAAAAAAAOD//w8AAAAAAAAA+P8fAAIAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD//wcAAAAAAAAA+P8fAAAAAAAAAAAA4P////8fAAAAAAAAAAAAAAAAAAAAAOD//wcAAAAAAAAA+P8fAAAAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD//wcAAAAAAAAA8P8PAAAAAAAAAAAAgP////8/AAAAAAAAAAAAAAAAAAAAAOD//wMAAAAAAAAA4P8HAAAAAAAAAAAAgP////8fAAAAAAAAAAAAAAAAAAAAAPD//wMAAAAAAAAA4P8HAAAAAAAAAAAAgP////8fAAAAAAAAAAAAAAAAAAAAAPD//wEAAAAAAAAAwP8DAAAAAAAAAAAAAP////8fAAAAAAAAAAAAAAAAAAAAAOD//wAAAAAAAAAAwP8BAAAAAAAAAAAAAP8D/P8PAAAAAAAAAAAAAAAAAAAAAPD/fwAAAAAAAAAAwH8AAAAAAAAAAAAAgP8A2P8HAAAAAAAAAAAAAAAAAAAAAPD/OwAAAAAAAAAAgAEAAAAAAAAAAAAAAAcA6P8HAAAAAAAAAAAAAAAAAAAAAPj/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP8DAAACAAAAAAAAAAAAAAAAAPj/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8DAAAEAAAAAAAAAAAAAAAAAPz/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8DAAAIAAAAAAAAAAAAAAAAAPj/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAAA4AAAAAAAAAAAAAAAAAPg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAPw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAPwHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAALAAAAAAAAAAAAAAAAAPwfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAIADAAAAAAAAAAAAAAAAAPgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAMABAAAAAAAAAAAAAAAAAPwHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAP4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAP4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAP4DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        },
      },
      us: {
        land: {
          lon0: -140,
          lat1: 62,
          step: 0.3,
          W: 300,
          H: 167,
          bits: "/////////////////////////w8AAAAAgMP//wMAIAIAAAAAAPD///////////////////////8/AAAAAAAA8P//AABgAAAAAAAA/////////////////////////wMAAAAAAID//w8AAAAAAAAAAPD///////////////////////8fAAAAAAAA+P//XwAAAAAAAAAA/////////////////////////wAAAAAAAID///8HAAAAAAAAAPD///////////////////////8HAAAAAAAA8P//PxjAAAAAAAAA////////////////////////fwAAAAAAAAD///8HAAwAAAAAAOD///////////////////////8HAAAAAAAI8P//fwDwAQAAAAAA/v//////////////////////fwAAAAAAAID///8HAD8AAAAAAAD///////////////////////8HAAAAAAAA/P///wDwDwAAAAAAgP///////////////////////wAAAAAAAOD///8/gP8BAAAAAADw7///////////////////////AAAAAAAA/v///wf/PwAAAAAAALj//////////////////////x8AAAAAAAD///////8DAAAAAACA////////////////////////AwAAAAAA4P///////wAAAAAAAODt/////////////////////z8AAAAAAAD8//////8fAAAAAAAA3Pz/////////////////////BwAAAAAAgP///////wEAAAAAAMD3//////////////////////9/AAAAAAD4//////8/AAAAAAAAsP///////////////////////38AAAAAgP///////wMAAAAAAAD6////////////////////////HwAAAAb4//////8fAAAAAAAAgPb///////////////////////8HAADwgP///////wcAAAAAAADg/f///////////////////////wEAAAD8////////AQAAAAAAAP7/////////////////////////AQAA8P///////z8AAAAAAADg+/////////////////////////8/AID/////////DwAAAAAAAHj9/////////////////////////x8A//////////8HAAAAAAAAAP//////////////////////////Af7//////////wcAAAAAAADw/////////////////////////w/A//////////8/AAAAAACAj/7/////////////////////////Afj//////////w8AAAAAAHjw/////////////////////////x+A/////////3/8BgAAAAAAB///////////////////////////Afj///////////8AAAAAAOCA//////////////////////////+A////////////HwAAAAAADPD/////////////////////////MfD///////////8BAAAAAIAB/////////////////////////z8A////////////HwAAAAAAMID/////////////////////////B+D///////////8BAAAAAAAA+P////////////////////////8B////////////DwAAAAAAAAD/////////////////////////P/D//////////z8AAAAAAAAA4P/////////////////////////n//////////8/HAAAAAAAAAD+////////////////////////////////////f+ABAAAAAAAAGP7///////////////////////////////////8BDwAAAAAAAAD/////////////////////////////////////D3gAAAAAAAAA8P////////////////////////////////8DAAbAAwAAAAAAAAD4+///////////////////////////////B3AAAPwBAAAAAAAAAH/+/////////////////////////////38APADgHwMAAAAAAADAH///////////////////////////////wAMfAP7/AAAAAAAAAPDn/////////////////////////////8P/AAD4/w8AAAAAAAAA/P3///////////////////////////+P/x8AwP//AgAAAAAAAIDk////////////////////////////f/7/AAD4/x8AAAAAAAAA+P/////////////////////////////z/wMA4P//AgAAAAAAAAD///////////////////////////////9/AAD+/z8AAAAAAAAA8P/////////////////////////////+/wcQAAC6BwAAAAAAAAD+////////////////////////////9/8/AAAAYHwAAAAAAAAA4P///////////////////////////////xcAAwBCAwAAAAAAAAD+//////////////////////////////9/BhgAAAAAAAAAAAAA4P///////////////////////////////9/HBwAAAAAAAAAAAAD+////////////////////////////////I34AAAAAAAAAAAAA4P//////////////////////////////////AQAAAAAAAAAAAAD+//////////////////////////////+f/wcAAAAAAAAAAAAA4P//////////////////////////////B/wfAAAAAAAAAAAAAAD+/////////////////////////////3/wHwAAAAAAAAAAAAAA4P//////////////////////////////wF8AAAAAAAAAAAAAAAD+/////////////////////////////wH8AAAAAAAAAAAAAAAA4P////////////////////////////8HwAMAAAAAAAAAAAAAAAD/////////////////////////////DwAQAAAAAAAAAAAAAAAA8P////////////////////////////8AAAAAAAAAAAAAAAAAAAD/////////////////////////////BwAAAAAAAAAAAAAAAAAA8P///////////////////////////38AAAAAAAAAAAAAAAAAAAD/////////////////////////////AwAAAAAAAAAAAAAAAAAA8P///////////////////////////38AAAAAAAAAAAAAAAAAAAD+////////////////////////////DwAAAAAAAAAAAAAAAAAA4P///////////////////////////x8AAAAAAAAAAAAAAAAAAAD+//////////////////////////8HAAAAAAAAAAAAAAAAAAAA4P///////////////////////////wEAAAAAAAAAAAAAAAAAAAD///////////////////////////8BAAAAAAAAAAAAAAAAAAAA8P//////////////////////////DwAAAAAAAAAAAAAAAAAAAAD+//////////////////////////8AAAAAAAAAAAAAAAAAAAAAwP//////////////////////////DwAAAAAAAAAAAAAAAAAAAAD8/////////////////////////38AAAAAAAAAAAAAAAAAAAAAwP//////////////////////////AgAAAAAAAAAAAAAAAAAAAAD4/////////////////////////w8AAAAAAAAAAAAAAAAAAAAAAP//////////////////////////AQAAAAAAAAAAAAAAAAAAAADg/////////////////////////w4AAAAAAAAAAAAAAAAAAAAAAPz///////////////////////9PAAAAAAAAAAAAAAAAAAAAAADA/////////////////////////wYAAAAAAAAAAAAAAAAAAAAAAPj///////////////////////8vAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////wEAAAAAAAAAAAAAAAAAAAAAAPD///////////////////////8/AAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////wMAAAAAAAAAAAAAAAAAAAAAAOD///////////////////////9fAAAAAAAAAAAAAAAAAAAAAAAA/P///////////////////////wcAAAAAAAAAAAAAAAAAAAAAAID///////////////////////8fAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////////8PAAAAAAAAAAAAAAAAAAAAAAAA4P//////////////////////HwAAAAAAAAAAAAAAAAAAAAAAAADg//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAwPD/////////////////////BwAAAAAAAAAAAAAAAAAAAAAAAAAA/v///////////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAID///////////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////8fAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////////////////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+//////////////////8DAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P//////////////////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8/P////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgA/+////////////////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAD44P///////////////38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/8////////////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwwf////////////+v/38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/4////////////AeD/DwAAAAAAAAAAAAAAAAAAAAAAAAAAAADgg////////////x8ADP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHjx////////fwD8AADgHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////8DADEAAPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODx////////HwAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPPz//////38AAAAAAPgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSH////////AQAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfPD//////w8AAAAAAPgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAP/P////9/AAAAAACAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/sD//////wMAAAAAAPgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAf8P////8/AAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8Af+/////wMAAAAAAOAPBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8wP////9/AAAAAAAA/gACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8/////wcAAAAAAMAPIAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgwP////9/AAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA74/////wcAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAf7///8/AAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/A/////wMAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgA/j///8fAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgA/////wEAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADuD///8fAAAAAAAAAIAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAB/P///wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOID///8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAD8P///wEAAAAAAPACABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+//8fAAAAAADw/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP///wEAAAAAwMM/AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8//8fAAAAAAAe/n8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///wEAAAAAcAT4DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID4//8/AAAAAABAAPwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wMAAPA/AAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw//8/AADA/wMAAOB/YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///wcAAP4fAAAA/A8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4////AADg/wEAAAD+AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///x8AAP4HAAAA8H8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4////AQDgfwAAAACDwHEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///z8AAP8HAAAAAAD4PwAAAAAAAAAAAAAAAAAAAAAAAAAAAADg////AwDwfwAAAAAAAP8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPj//38AwP8HAAAAAADw/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//P8D8PwAAAAAACP5/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD////H//8DAAAAfMD/P4IPAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////PwAAAIAfADgAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4//////8BAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA//////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOD/////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4////BwAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7A/38ADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvj///8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD///8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P///wEAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8fAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P///wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg//8fAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuP8PAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/wAAAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwPAAAAADwCAAAAAAAAAAA=",
        },
        focus: {
          lon0: -140,
          lat1: 62,
          step: 0.3,
          W: 300,
          H: 167,
          bits: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOABCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfvABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADPPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw7wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD3AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD6PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgPYfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg/QEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg+wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//////////////8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3//////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDg////////////////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////////////////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////8fAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAAD+////////////////////AwAAAAAAgA8AAAAAAAAAAAAAAAAA4P////////////////////8AAAAAAAD8AQAAAAAAAAAAAAAAAAD+////////////////////PwAAAAAA4B8AAAAAAAAAAAAAAAAA4P////////////////////8HAAAAAAD/AQAAAAAAAAAAAAAAAAD+/////////////////////wAAAAAA8B8AAAAAAAAAAAAAAAAA4P////////////////////8fAAAAAID/AwAAAAAAAAAAAAAAAAD+/////////////////////wcAAAAA/D8AAAAAAAAAAAAAAAAA4P//////////////////////AAAA/v//BwAAAAAAAAAAAAAAAAD+/////////////////////w8AAPj//38AAAAAAAAAAAAAAAAA4P//////////////////////AADA////AAAAAAAAAAAAAAAAAAD+/////////////////////x8AAP///wEAAAAAAAAAAAAAAAAA4P//////////////////////AQD4//8HAAAAAAAAAAAAAAAAAAD//////////////////////x+A////DwAAAAAAAAAAAAAAAAAA8P//////////////////////APj///8AAAAAAAAAAAAAAAAAAAD//////////////////////w+A////BwAAAAAAAAAAAAAAAAAA8P//////////////////////AP7//38AAAAAAAAAAAAAAAAAAAD//////////////////////wP8////AwAAAAAAAAAAAAAAAAAA8P////////////////////8//P///38AAAAAAAAAAAAAAAAAAAD+////////////////////////////DwAAAAAAAAAAAAAAAAAA4P///////////////////////////x8AAAAAAAAAAAAAAAAAAAD+//////////////////////////8HAAAAAAAAAAAAAAAAAAAA4P///////////////////////////wEAAAAAAAAAAAAAAAAAAAD///////////////////////////8BAAAAAAAAAAAAAAAAAAAA8P//////////////////////////DwAAAAAAAAAAAAAAAAAAAAD+//////////////////////////8AAAAAAAAAAAAAAAAAAAAAwP//////////////////////////DwAAAAAAAAAAAAAAAAAAAAD8/////////////////////////38AAAAAAAAAAAAAAAAAAAAAwP//////////////////////////AgAAAAAAAAAAAAAAAAAAAAD4/////////////////////////w8AAAAAAAAAAAAAAAAAAAAAAP//////////////////////////AQAAAAAAAAAAAAAAAAAAAADg/////////////////////////w4AAAAAAAAAAAAAAAAAAAAAAPz///////////////////////9PAAAAAAAAAAAAAAAAAAAAAADA/////////////////////////wYAAAAAAAAAAAAAAAAAAAAAAPj///////////////////////8vAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////wEAAAAAAAAAAAAAAAAAAAAAAPD///////////////////////8/AAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////wMAAAAAAAAAAAAAAAAAAAAAAOD///////////////////////9fAAAAAAAAAAAAAAAAAAAAAAAA/P///////////////////////wcAAAAAAAAAAAAAAAAAAAAAAID///////////////////////8fAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////////8PAAAAAAAAAAAAAAAAAAAAAAAA4P//////////////////////HwAAAAAAAAAAAAAAAAAAAAAAAADg//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAwPD/////////////////////BwAAAAAAAAAAAAAAAAAAAAAAAAAA/v///////////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAID///////////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD/////////////////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////////////////8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8////////////////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPw/8P////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8////////////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///////////38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw////////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///////+v/38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA////////AeD/DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPz5/////x8ADP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAD/z/fwD8AADgHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCA//8DADEAAPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPj/HwAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/38AAAAAAPgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD/AQAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/g8AAAAAAPgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMB/AAAAAACAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AMAAAAAAPgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AMAAAAAAOAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAcAAAAAAMAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        },
      },
      bd: {
        land: {
          lon0: 72,
          lat1: 34,
          step: 0.12,
          W: 300,
          H: 183,
          bits: "//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////v///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+///////////////////////////////////////////////////P//////////////////////////////////////////////////////////////////////////////////////////////////+/4//////////////////////////////////////////////+/Qf///////////////////////////////////////////////5/0////////////////////////////////////////////////Cf7/////////////////////5////////////////////////9/g/////////////////////z////////////////////////+fAP7/////////////////////4f/////////////////////7zwHg/////////////////////x/+////////////////////vVsIAP7/////////////////////4////////////////////887AADg/////////////////////z/8//////////////////8PAAAAAP7/////////////////////4///////////////////PwAAAACA/////////////////////xP+//////////////////8BAAAAAPj///////////////////8fwf//////////////////DwAAAACA/////////////////////wD8//////////////////8AAAAAAPD///////////////////8PgP//////////////////DwAAAAAA////////////////////PwD4//////////////////8AAAAAAOD//////////////////78AgP//////////////////HwAAAAAA/P//////////////////AwD4//////////////////8BAAAAAMD//////////////////x8AgP//////////////////DwAAAAAA+P//////////////////AAD4/////////////////38AAAAAAAD9/////////////////w8AwP//////////////////AwAAAAAA4P////////////////9/AAD8/////////////////x8AAAAAAAD4/////////////////wMAwP//////////////////AAAAAAAAwP3///////////////8fAAD8/////////////////wcAAAAAAABQ////////////////fwAAwP///////////////38GAAAAAAAAAPD///////////////8HAAD8////////////////CwAAAAAAAAAA/v//////////////PwAAwP///////////////38AAAAAAAAAAMD///////////////8DAAD8////////////////AQAAAAAAAAAA/v//////////////PwAAgP///////////////w8AAAAAAAAAAPj///////////////8DAAD8//////////////9/AAAAAAAAAAAA////////////////HwAAgP///////////////wMAAAAAAAAAAPD///////////////8BAADw//////////////8/AAAAAAAAAAAA9P//////////////DwAAgP///////////////wEAAAAAAAAAABj///////////////8BAAD4//////////////8PAAAAAAAAAAAA4f//////////////PwAAgP//////////////fwAAAAAAAAAAAAD+//////////////8DAADw//////////////8DAAAAAAAAAAAAwP//////////////fwAAAP//////////////HwAAAAAAAAAAAAD8//////////////8PAADw//////////////8AAAAAAAAAAAAAgP///////////////wEAAP//////////////AwAAAAAAAAAAAAD4//////////////9/AADw/////////////w8AAAAAAAAAAAAAgP///////////////wcAAP7/////////////AAAAAAAAAAAAAAD4//////////////9/AADg/////////////wcAAAAAAAAAAAAAAP///////////////wcAAP7///////////8/AAAAAAAAAAAAAADw////////////////AADA/////////////wAAAAAAAAAAAAAAAP///////////////x8AAPz///////////8DAAAAAAAAAAAAAADw////////////////AQDA////////////DwAAAAAAAAAAAAAAAP///////////////38AAPz//////////38AAAAAAAAAAAAAAAD4/3/+////////////DwDA////////////AwAAAAAAAAAAAAAAgP//z/////////////8BAPz//////////z8AAAAAAAAAAAAAAAD4/3/8////////////HwCA////////////AwAAAAAAAAAAAAAAwP//x/////////////8HAPj//////////z8AAAAAAAAAAAAAAAD8/z/4/////////////wCA////////////AQAAAAAAAAAAAAAAwP+/gf////////////8fAPj//////////wcAAAAAAAAAAAAAAAD+/wPw/////////////wMA//////////8BAAAAAAAAAAAAAAAA4P8fAP//////////////APD/////////HwAAAAAAAAAAAAAAAAD+fwDg/////////////w8A//////////8BAAAAAAAAAAAAAAAA4P8DAP7/////////////AOD/////////DwAAAAAAAAAAAAAAAACgHwDA/////////////w8A/v///////2MAAAAAAAAAAAAAAAAAANgAAPz/////////////AMD///////8fAAAAAAAAAAAAAAAAAAAAAADA/////////////w8A+P///////wEAAAAAAAAAAAAAAAAAAAAAAPj/////////////AID///////8PAAAAAAAAAAAAAAAAAAAAAACA/////////////w8A+P///////wAAAAAAAAAAAAAAAAAAAAAAAPj/////////////AAD///////8PAAAAAAAAAAAAAAAAAAAAAACA/////////////w8A8P//////fwAAAAAAAAAAAAAAAAAAAAAAAPj/////////////AAD+//////8HAAAAAAAAAAAAAAAAAAAAAACA/////////////w8A4P///////wAAAAAAAAAAAAAAAAAAAAAAAPj/////////////AAD8//////8PAAAAAAAAAAAAAAAAAAAAAAAA/////////////w8AgP///////wAAAAAAAAAAAAAAAAAAAAAAAPD/////////////AADw//////8PAAAAAAAAAAAAAAAAAAAAAAAA/////////////w8AAP///////wAAAAAAAAAAAAAAAAAAAAAAAPD/////////////AADw//////8PAAAAAAAAAAAAAAAAAAAAAAAA/v///////////w8AAP7//////wAAAAAAAAAAAAAAAAAAAAAAAOD/////////////AADg//////8PAAAAAAAAAAAAAAAAAAAAAAAA/v///////////w8AAP7//////wEAAAAAAAAAAAAAAAAAAAAAAOD/////////////AADA//////8fAAAAAAAAAAAAAAAAAAAAAAAA/v///////////w8AAPz//////wEAAAAAAAAAAAAAAAAAAAAAAID/////////////AADA//////8PAAAAAAAAAAAAAAAAgAAAAAAA8P///////////w8AAPz//////wEAAAAAAAAAAAAAAAAMAAAAAAD/P+D/////////AACA//////8/AAAAAAAAAAAAAAAAwAAAAAAA8P8B/v///////w8AAPj//////wMAAAAAAAAAAAAAAAAMAAAAAAD+P+D/////////AACA//////8fAAAAAAAAAAAAAAAAYAAAAAAA4P8D/v///////w8AAPj//////wEAAAAAAAAAAAAAAAADAAAAAAD8P+D/////////AAAA//////8fAAAAAAAAAAAAAAAAYAAAAAAAwP8B/v///////w8AAPD//////wEAAAAAAAAAAAAAAAAGAAAAAAD8H+D/////////AAAA//////8PAAAAAAAAAAAAAAAAYAAAAAAAyP8BAP7//////w8AAOD//////wAAAAAAAAAAAAAAAAAHAAAAAID8PwCA////////AAAA/v////8HAAAAAAAAAAAAAAAAIAAAAAAAwf8DAPD//////w8AAMD/////fwAAAAAAAAAAAAAAAAACAAAAACD8HwAA/v//////AAAA/P////8DAAAAAAAAAAAAAAAAMAAAAAAAwP8BABD//////w8=",
        },
        focus: {
          lon0: 72,
          lat1: 34,
          step: 0.12,
          W: 300,
          H: 183,
          bits: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+McAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID/HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P//HwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P///x8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P///w8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8//8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4//8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP//HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8///AAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP//DxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4//vgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP//Hz8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg///jAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+/fz8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg//P/AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7//38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg/+/4BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP6/QX8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/5/0BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPz/CX4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/9/gBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPyfAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAzwHgDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgIAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        },
      },
    };
    const THEMES = window.THEMES,
      PUBS = window.PUBS;
    const themeOf = (id) => THEMES.find((t) => t.id === id) || THEMES[0];
    const RAD = Math.PI / 180;
    const esc = (s) =>
      String(s).replace(
        /[&<>"]/g,
        (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c],
      );

    // ---- Land layers: coarse world, plus finer detail for the U.S. and Bangladesh when zoomed in ----
    const decode = (m) => {
      const s = atob(m.bits);
      return (k) => s.charCodeAt(k >> 3) & (1 << (k & 7));
    };
    const layer = (m, focus) => ({
      m,
      isLand: decode(m),
      isFocus: focus ? decode(focus) : null,
      lon1: m.lon0 + m.W * m.step,
      lat0: m.lat1 - m.H * m.step,
    });
    const WORLD = layer(MAPS.world.land);
    const DETAIL = [
      layer(MAPS.us.land, MAPS.us.focus),
      layer(MAPS.bd.land, MAPS.bd.focus),
    ];

    // ---- View state: map center and zoom ----
    const HOME = { lon: -15, lat: 14 },
      MAXZ = 16;
    let cx = HOME.lon,
      cy = HOME.lat,
      zoom = 1;
    const size = () => [box.clientWidth, box.clientHeight];
    function baseSpan() {
      const [w, h] = size();
      return Math.max(125, 250 / (w / h));
    } // whole study area fits at zoom 1
    function scale() {
      const [, h] = size();
      return h / (baseSpan() / zoom);
    } // pixels per degree of latitude
    const kx = () => Math.cos(Math.max(-60, Math.min(60, cy)) * RAD); // keeps shapes natural when zoomed
    function toPx(lon, lat) {
      const [w, h] = size(),
        s = scale();
      return [w / 2 + (lon - cx) * kx() * s, h / 2 - (lat - cy) * s];
    }
    function toLonLat(x, y) {
      const [w, h] = size(),
        s = scale();
      return [cx + (x - w / 2) / (kx() * s), cy - (y - h / 2) / s];
    }
    function clampView() {
      zoom = Math.max(1, Math.min(MAXZ, zoom));
      cx = Math.max(-170, Math.min(170, cx));
      cy = Math.max(-55, Math.min(78, cy));
      if (zoom === 1) {
        cx = HOME.lon;
        cy = HOME.lat;
      }
    }

    // ---- Drawing ----
    const canvas = box.querySelector("canvas"),
      ctx = canvas.getContext("2d");
    function drawLayer(L, clip, dim) {
      // a coarse cell that has grown large on screen is filled with several small dots, so all zoom levels share one texture
      const [w, h] = size(),
        s = scale(),
        m = L.m,
        cell = m.step * s * kx(),
        n = Math.max(1, Math.round(cell / 4.5));
      const sub = cell / n,
        dot = Math.min(4, Math.max(1.2, sub * 0.62)),
        cellY = m.step * s,
        subY = cellY / n;
      const [lonA, latB] = toLonLat(0, 0),
        [lonB, latA] = toLonLat(w, h);
      const i0 = Math.max(0, Math.floor((lonA - m.lon0) / m.step) - 1),
        i1 = Math.min(m.W - 1, Math.ceil((lonB - m.lon0) / m.step) + 1);
      const j0 = Math.max(0, Math.floor((m.lat1 - latB) / m.step) - 1),
        j1 = Math.min(m.H - 1, Math.ceil((m.lat1 - latA) / m.step) + 1);
      for (let j = j0; j <= j1; j++)
        for (let i = i0; i <= i1; i++) {
          const k = j * m.W + i;
          if (!L.isLand(k)) continue;
          const lon = m.lon0 + m.step * (i + 0.5),
            lat = m.lat1 - m.step * (j + 0.5);
          if (clip && clip(lon, lat)) continue;
          const [x, y] = toPx(lon, lat);
          ctx.fillStyle = L.isFocus
            ? L.isFocus(k)
              ? "rgba(186,168,212,.95)"
              : "rgba(186,168,212,.28)"
            : dim
              ? "rgba(186,168,212,.28)"
              : "rgba(186,168,212,.6)";
          if (n === 1) {
            ctx.fillRect(x - dot / 2, y - dot / 2, dot, dot);
            continue;
          }
          for (let a = 0; a < n; a++)
            for (let b = 0; b < n; b++)
              ctx.fillRect(
                x - cell / 2 + (a + 0.5) * sub - dot / 2,
                y - cellY / 2 + (b + 0.5) * subY - dot / 2,
                dot,
                dot,
              );
        }
    }
    function draw() {
      const [w, h] = size();
      if (!w) return;
      const dpr = window.devicePixelRatio || 1;
      if (canvas.width !== Math.round(w * dpr)) {
        canvas.width = w * dpr;
        canvas.height = h * dpr;
      }
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.fillStyle = "#3C1053";
      ctx.fillRect(0, 0, w, h);
      // use a detailed layer once its dots are big enough to read
      const on = DETAIL.filter((L) => L.m.step * scale() * kx() >= 2.4);
      const inside = (lon, lat) =>
        on.some(
          (L) =>
            lon >= L.m.lon0 && lon < L.lon1 && lat >= L.lat0 && lat < L.m.lat1,
        );
      drawLayer(WORLD, on.length ? inside : null, on.length > 0); // match the dimmed neighbors once a detailed country is shown
      on.forEach((L) => drawLayer(L));
      placePins();
      zoomOut.disabled = zoom <= 1;
      zoomIn.disabled = zoom >= MAXZ;
    }

    // ---- Publication pins ----
    const pinLayer = box.querySelector(".pins"),
      pop = box.querySelector(".pop"),
      pins = [];
    PUBS.forEach((pub, n) =>
      pub.points.forEach(([lon, lat]) => {
        const b = document.createElement("button");
        b.className = "pin";
        b.type = "button";
        b.style.setProperty("--c", themeOf(pub.theme).color);
        b.setAttribute("aria-label", pub.title + ", " + pub.place);
        b.dataset.pub = n;
        b.dataset.theme = pub.theme;
        pinLayer.appendChild(b);
        pins.push({ b, lon, lat, pub });
      }),
    );
    function placePins() {
      const [w, h] = size();
      pins.forEach((p) => {
        const [x, y] = toPx(p.lon, p.lat);
        p.b.style.left = x + "px";
        p.b.style.top = y + "px";
        p.b.hidden = x < -8 || x > w + 8 || y < -8 || y > h + 8;
      });
    }

    // ---- Pop-up ----
    let hideTimer = null,
      pinned = null;
    function showPop(p) {
      clearTimeout(hideTimer);
      const t = themeOf(p.pub.theme),
        meta = [p.pub.journal, p.pub.year].filter(Boolean).join(", ");
      pop.innerHTML =
        '<span class="pop-theme" style="--c:' +
        t.color +
        '">' +
        esc(t.name) +
        "</span>" +
        "<h4>" +
        esc(p.pub.title) +
        "</h4>" +
        '<p class="pop-meta">' +
        esc(p.pub.place) +
        (meta ? "<br>" + esc(meta) : "") +
        "</p>" +
        (p.pub.figure
          ? '<img src="' +
            esc(p.pub.figure) +
            '" alt="Figure from ' +
            esc(p.pub.title) +
            '">'
          : "") +
        "<p>" +
        esc(p.pub.summary) +
        "</p>" +
        (p.pub.link
          ? '<a href="' +
            esc(p.pub.link) +
            '" target="_blank" rel="noopener">Read the paper</a>'
          : "");
      pop.hidden = false;
      const [w] = size(),
        x = p.b.offsetLeft,
        y = p.b.offsetTop,
        pw = pop.offsetWidth;
      pop.style.left =
        (x + 16 + pw < w ? x + 16 : Math.max(0, x - 16 - pw)) + "px";
      pop.style.top = Math.max(0, y - 24) + "px";
    }
    function hidePop(now) {
      if (pinned) return;
      clearTimeout(hideTimer);
      hideTimer = setTimeout(() => (pop.hidden = true), now ? 0 : 200);
    }
    function closePop() {
      pinned = null;
      pop.hidden = true;
    }
    pins.forEach((p) => {
      p.b.addEventListener("mouseenter", () => {
        if (!dragging) showPop(p);
      });
      p.b.addEventListener("mouseleave", () => hidePop());
      p.b.addEventListener("focus", () => showPop(p));
      p.b.addEventListener("blur", () => hidePop());
      p.b.addEventListener("click", (e) => {
        if (moved) return;
        pinned = pinned === p ? null : p;
        showPop(p);
      }); // tap keeps it open
    });
    pop.addEventListener("mouseenter", () => clearTimeout(hideTimer));
    pop.addEventListener("mouseleave", () => hidePop());
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closePop();
    });
    document.addEventListener("click", (e) => {
      if (pinned && !box.contains(e.target)) closePop();
    });

    // ---- Zoom and pan ----
    let anim = null;
    function zoomAt(factor, px, py, smooth) {
      // keep the point under (px, py) fixed
      const [w, h] = size();
      px = px ?? w / 2;
      py = py ?? h / 2;
      const [lon, lat] = toLonLat(px, py),
        z0 = zoom,
        c0 = [cx, cy];
      const z1 = Math.max(1, Math.min(MAXZ, zoom * factor));
      const target = () => {
        zoom = z1;
        const [lon2, lat2] = toLonLat(px, py);
        const t = [cx + lon - lon2, cy + lat - lat2];
        return t;
      };
      zoom = z1;
      cx = c0[0];
      cy = c0[1];
      const [tx, ty] = target();
      zoom = z0;
      closePop();
      cancelAnimationFrame(anim);
      if (!smooth) {
        zoom = z1;
        cx = tx;
        cy = ty;
        clampView();
        draw();
        return;
      }
      const start = performance.now();
      (function step(now) {
        const q = Math.min(1, (now - start) / 250),
          e = 1 - (1 - q) ** 3;
        zoom = z0 * Math.pow(z1 / z0, e);
        cx = c0[0] + (tx - c0[0]) * e;
        cy = c0[1] + (ty - c0[1]) * e;
        clampView();
        draw();
        if (q < 1) anim = requestAnimationFrame(step);
      })(start);
    }
    const zoomIn = box.querySelector(".zoom-in"),
      zoomOut = box.querySelector(".zoom-out"),
      zoomReset = box.querySelector(".zoom-reset");
    zoomIn.addEventListener("click", () => zoomAt(2, null, null, true));
    zoomOut.addEventListener("click", () => zoomAt(0.5, null, null, true));
    zoomReset.addEventListener("click", () =>
      zoomAt(1 / zoom, null, null, true),
    );
    box.addEventListener("dblclick", (e) => {
      if (e.target.closest(".pin, .pop, .zoom")) return;
      const r = box.getBoundingClientRect();
      zoomAt(2, e.clientX - r.left, e.clientY - r.top, true);
    });

    // mouse wheel zooms around the pointer; at the zoom limits the page scrolls as usual
    box.addEventListener(
      "wheel",
      (e) => {
        if ((e.deltaY > 0 && zoom <= 1) || (e.deltaY < 0 && zoom >= MAXZ))
          return;
        e.preventDefault();
        const r = box.getBoundingClientRect();
        zoomAt(
          Math.exp(-e.deltaY * 0.0025),
          e.clientX - r.left,
          e.clientY - r.top,
          false,
        );
      },
      { passive: false },
    );

    // drag to pan; two fingers to pinch-zoom
    const pts = new Map();
    let dragging = false,
      moved = false,
      last = null,
      pinch = null;
    box.addEventListener("pointerdown", (e) => {
      if (e.target.closest(".pop, .zoom")) return;
      pts.set(e.pointerId, [e.clientX, e.clientY]);
      moved = false;
      if (pts.size === 1) {
        dragging = true;
        last = [e.clientX, e.clientY];
      }
      if (pts.size === 2) {
        const [a, b] = [...pts.values()];
        pinch = { d: Math.hypot(a[0] - b[0], a[1] - b[1]), z: zoom };
      }
    });
    addEventListener("pointermove", (e) => {
      if (!pts.has(e.pointerId)) return;
      pts.set(e.pointerId, [e.clientX, e.clientY]);
      const r = box.getBoundingClientRect();
      if (pts.size === 2 && pinch) {
        const [a, b] = [...pts.values()],
          d = Math.hypot(a[0] - b[0], a[1] - b[1]);
        zoomAt(
          (pinch.z * d) / pinch.d / zoom,
          (a[0] + b[0]) / 2 - r.left,
          (a[1] + b[1]) / 2 - r.top,
          false,
        );
        moved = true;
        return;
      }
      if (!dragging || zoom <= 1) return;
      const dx = e.clientX - last[0],
        dy = e.clientY - last[1];
      if (Math.abs(dx) + Math.abs(dy) > 2) {
        moved = true;
        box.classList.add("grabbing");
        closePop();
      }
      last = [e.clientX, e.clientY];
      const s = scale();
      cx -= dx / (kx() * s);
      cy += dy / s;
      clampView();
      draw();
    });
    const end = (e) => {
      pts.delete(e.pointerId);
      if (pts.size < 2) pinch = null;
      if (!pts.size) {
        dragging = false;
        box.classList.remove("grabbing");
        setTimeout(() => (moved = false), 0);
      }
    };
    addEventListener("pointerup", end);
    addEventListener("pointercancel", end);

    // ---- Theme list (left column): hover to preview, click to filter ----
    const list = document.getElementById("theme-list");
    THEMES.forEach((t) => {
      const count = PUBS.filter((p) => p.theme === t.id).length;
      const li = document.createElement("li");
      li.innerHTML =
        '<button type="button" class="theme" data-theme="' +
        t.id +
        '" style="--c:' +
        t.color +
        '" aria-pressed="false">' +
        '<span class="dot" aria-hidden="true"></span><span class="tname">' +
        esc(t.name) +
        "</span>" +
        '<span class="tcount">' +
        count +
        (count === 1 ? " publication" : " publications") +
        "</span>" +
        '<span class="ttext">' +
        esc(t.text) +
        "</span></button>";
      list.appendChild(li);
    });
    let active = null,
      hoverTheme = null;
    const themeBtns = [...list.querySelectorAll(".theme")];
    function styleThemes() {
      const show = hoverTheme || active;
      pins.forEach((p) =>
        p.b.classList.toggle("dim", !!show && p.pub.theme !== show),
      );
      themeBtns.forEach((b) => {
        const on = active === b.dataset.theme;
        b.classList.toggle("on", on);
        b.setAttribute("aria-pressed", on);
      });
    }
    themeBtns.forEach((b) => {
      b.addEventListener("mouseenter", () => {
        hoverTheme = b.dataset.theme;
        styleThemes();
      });
      b.addEventListener("mouseleave", () => {
        hoverTheme = null;
        styleThemes();
      });
      b.addEventListener("click", () => {
        active = active === b.dataset.theme ? null : b.dataset.theme;
        styleThemes();
      });
    });

    addEventListener("resize", () => {
      clampView();
      draw();
    });
    addEventListener("hashchange", () => setTimeout(draw, 0)); // the Research tab may have been hidden
    draw();
    return true;
  }
  // Research lives in pages/research.html: build the map now if it's already on the page,
  // otherwise as soon as main.js finishes loading it.
  if (!initResearchMap())
    addEventListener("page:loaded", (e) => {
      if (e.detail && e.detail.id === "page-research") initResearchMap();
    });
})();
